{{- if .Values.dcm4chee.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "care-radiology.fullname" . }}-dcm4chee
  labels:
    app.kubernetes.io/name: {{ include "care-radiology.name" . }}-dcm4chee
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: pacs
spec:
  type: {{ .Values.dcm4chee.service.type }}
  ports:
  - port: {{ .Values.dcm4chee.service.ports.http }}
    targetPort: http
    protocol: TCP
    name: http
  - port: {{ .Values.dcm4chee.service.ports.dicom }}
    targetPort: dicom
    protocol: TCP
    name: dicom
  - port: {{ .Values.dcm4chee.service.ports.hl7 }}
    targetPort: hl7
    protocol: TCP
    name: hl7
  selector:
    app.kubernetes.io/name: {{ include "care-radiology.name" . }}-dcm4chee
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
