{{- if and .Values.dcm4chee.enabled .Values.dcm4chee.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "care-radiology.fullname" . }}-dcm4chee
  labels:
    app.kubernetes.io/name: {{ include "care-radiology.name" . }}-dcm4chee
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dcm4chee.persistence.size }}
  {{- if .Values.global.storageClass }}
  storageClassName: {{ .Values.global.storageClass }}
  {{- end }}
{{- end }}
