{{- if .Values.nginx.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "care-radiology.fullname" . }}-nginx-config
  labels:
    app.kubernetes.io/name: {{ include "care-radiology.name" . }}-nginx
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  nginx.conf: |
{{ .Values.nginx.config.nginx.conf | indent 4 }}
{{- end }}
