from care_radiology.settings import plugin_settings

DCM4CHEE_BASEURL = plugin_settings.CARE_RADIOLOGY_DCM4CHEE_DICOMWEB_BASEURL

MPPS_STATUS_SCAN_STARTED = "SCAN_STARTED"
MPPS_STATUS_SCAN_COMPLETED = "SCAN_COMPLETED"
MPPS_STATUS_DISCONTINUED = "DISCONTINUED"

VALID_MPPS_STATUSES = [MPPS_STATUS_SCAN_STARTED, MPPS_STATUS_SCAN_COMPLETED, MPPS_STATUS_DISCONTINUED]

DICOM_FILE_EXTENSIONS = (".dcm", ".dicom")

DICOM_STUDY_CACHE_KEY_TEMPLATE = "radiology:dicom:study:{}"
