# Generated by Django 6.0 on 2026-05-11 07:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0002_alter_dicomstudy_table_and_more'),
        ('emr', '0077_tagconfig_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='radiologyservicerequest',
            constraint=models.UniqueConstraint(fields=('service_request', 'dicom_study'), name='unique_service_request_dicom_study'),
        ),
    ]
