# Generated by Django 6.0 on 2026-06-19 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0003_radiologyservicerequest_unique_service_request_dicom_study'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanprotocol',
            name='body_part',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='scanprotocol',
            name='modality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyreport',
            name='body_part',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='studyreport',
            name='modality',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='body_part',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='template',
            name='modality',
            field=models.CharField(max_length=255),
        ),
    ]
