# Generated by Django 6.0 on 2026-09-07 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0006_observationtemplate_unique_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodypart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='modality',
        ),
        migrations.RemoveField(
            model_name='bodypart',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='modalitytype',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='modalitytype',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='scanprotocol',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scanprotocol',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='template',
            name='scan_protocol',
        ),
        migrations.RemoveField(
            model_name='studyreport',
            name='scan_protocol',
        ),
        migrations.RemoveField(
            model_name='studyreport',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studyreport',
            name='study',
        ),
        migrations.RemoveField(
            model_name='studyreport',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='studyreportaudit',
            name='study_report',
        ),
        migrations.RemoveField(
            model_name='studyreportaudit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='studyreportaudit',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='template',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='template',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='observationtemplate',
            new_name='care_radiol_observa_a96e2e_idx',
            old_name='care_radiol_obs_def_act_def_idx',
        ),
        migrations.DeleteModel(
            name='BodyPart',
        ),
        migrations.DeleteModel(
            name='ModalityType',
        ),
        migrations.DeleteModel(
            name='ScanProtocol',
        ),
        migrations.DeleteModel(
            name='StudyReport',
        ),
        migrations.DeleteModel(
            name='StudyReportAudit',
        ),
        migrations.DeleteModel(
            name='Template',
        ),
    ]
