# Generated by Django 6.0 on 2026-09-11 10:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0007_remove_bodypart_created_by_remove_bodypart_modality_and_more'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessionSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modality_code', models.CharField(blank=True, max_length=100)),
                ('year', models.PositiveSmallIntegerField()),
                ('last_value', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='radiology_accession_sequences', to='facility.facility')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('facility', 'modality_code', 'year'), name='uniq_facility_modality_year')],
            },
        ),
    ]
