# Generated by Django 6.0 on 2026-09-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0008_accessionsequence'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='radiologyservicerequest',
            name='unique_service_request_dicom_study',
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='radiology_service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studies', to='care_radiology.radiologyservicerequest'),
        ),
    ]
