# Generated by Django 6.0 on 2026-09-15 11:05

from django.db import migrations


def backfill_studies_and_dedupe_rsr(apps, schema_editor):
    RadiologyServiceRequest = apps.get_model('care_radiology', 'RadiologyServiceRequest')
    DicomStudy = apps.get_model('care_radiology', 'DicomStudy')

    # Point each DicomStudy at the RSR that used to link to it via the old dicom_study FK.
    for rsr in RadiologyServiceRequest.objects.exclude(dicom_study__isnull=True):
        DicomStudy.objects.filter(id=rsr.dicom_study_id).update(radiology_service_request=rsr)

    # Only one RSR per service_request can survive the upcoming unique constraint.
    # Keep the oldest row per service_request, move its siblings' studies onto it, drop the rest.
    for sr_id in (
        RadiologyServiceRequest.objects.exclude(service_request__isnull=True)
        .values_list('service_request_id', flat=True)
        .distinct()
    ):
        rows = list(
            RadiologyServiceRequest.objects.filter(service_request_id=sr_id).order_by('created_date')
        )
        keeper, duplicates = rows[0], rows[1:]
        if not duplicates:
            continue
        DicomStudy.objects.filter(radiology_service_request__in=duplicates).update(
            radiology_service_request=keeper
        )
        RadiologyServiceRequest.objects.filter(id__in=[d.id for d in duplicates]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0009_remove_radiologyservicerequest_unique_service_request_dicom_study_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_studies_and_dedupe_rsr, migrations.RunPython.noop),
    ]
