# Generated by Django 6.0 on 2026-09-15 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0010_backfill_radiologyservicerequest_studies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radiologyservicerequest',
            name='raw_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='radiologyservicerequest',
            name='service_request',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_service_requests', to='emr.servicerequest', unique=True),
        ),
        migrations.RemoveField(
            model_name='radiologyservicerequest',
            name='dicom_study',
        ),
    ]
