# Generated by Django 6.0 on 2026-09-15 12:17

from django.db import migrations, models


def backfill_status(apps, schema_editor):
    from care_radiology.settings import plugin_settings

    RadiologyServiceRequest = apps.get_model('care_radiology', 'RadiologyServiceRequest')
    ServiceRequest = apps.get_model('emr', 'ServiceRequest')

    # Pre-existing rows were only ever created once a study was linked (the old
    # lazy get_or_create path), so under the old code their mere existence means
    # the request had already reached COMPLETED.
    RadiologyServiceRequest.objects.update(status='COMPLETED')

    # Radiology-category service requests created before this migration never
    # got an eagerly-created RadiologyServiceRequest row (the signal only fires
    # on creation), so MPPS/status updates for them would silently no-op.
    radiology_sr_ids = ServiceRequest.objects.filter(
        category=plugin_settings.CARE_RADIOLOGY_RADIOLOGY_CATEGORY
    ).values_list('id', flat=True)
    existing_sr_ids = RadiologyServiceRequest.objects.filter(
        service_request_id__in=radiology_sr_ids
    ).values_list('service_request_id', flat=True)
    missing_sr_ids = set(radiology_sr_ids) - set(existing_sr_ids)
    RadiologyServiceRequest.objects.bulk_create(
        [RadiologyServiceRequest(service_request_id=sr_id, status='ACTIVE') for sr_id in missing_sr_ids]
    )


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0011_alter_radiologyservicerequest_raw_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='radiologyservicerequest',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='ACTIVE', max_length=20),
        ),
        migrations.RunPython(backfill_status, migrations.RunPython.noop),
    ]
