# Generated by Django 6.0 on 2026-09-17 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0012_radiologyservicerequest_status'),
        ('emr', '0082_remove_encounter_encounter_class_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dicomstudy',
            name='archive_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archived_dicom_studies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='archived_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dicomstudy',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='radiologyservicerequest',
            name='service_request',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='radiology_service_requests', to='emr.servicerequest'),
        ),
    ]
