# Generated by Django 6.0 on 2026-09-30 09:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_radiology', '0013_dicomstudy_archive_reason_dicomstudy_archived_by_and_more'),
        ('emr', '0082_remove_encounter_encounter_class_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dicomstudy',
            name='unique_patient_study_uid',
        ),
        migrations.AddConstraint(
            model_name='dicomstudy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_archived', False)), fields=('patient', 'dicom_study_uid'), name='unique_patient_active_study_uid'),
        ),
    ]
