# Generated by Django 6.0 on 2026-09-30 05:18

from django.db import migrations, models


def backfill_accession_number(apps, schema_editor):
    RadiologyServiceRequest = apps.get_model("care_radiology", "RadiologyServiceRequest")
    for rsr in RadiologyServiceRequest.objects.exclude(service_request__isnull=True).select_related("service_request"):
        accession_number = rsr.service_request.meta.get("accession_number")
        if accession_number:
            rsr.accession_number = accession_number
            rsr.save(update_fields=["accession_number"])


class Migration(migrations.Migration):
    dependencies = [
        ("care_radiology", "0013_dicomstudy_archive_reason_dicomstudy_archived_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="radiologyservicerequest",
            name="accession_number",
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.RunPython(backfill_accession_number, migrations.RunPython.noop),
    ]
